// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cigxgrewgaocyfyutrth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZ3hncmV3Z2FvY3lmeXV0cnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjIwMzIsImV4cCI6MjA3MTI5ODAzMn0.a9JVNhRR-VoflalmR7rndIgr-rwqcnOKsjB-_ALsLJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});